# install commandline utils
brew 'asciinema'
brew 'archey'
brew 'httpie'
brew 'mongodb'
brew 'node'
brew 'nvm'
brew 'thefuck'
brew 'tree'
brew 'tmux'
brew 'vim'
brew 'wget'

# install cask
tap 'caskroom/cask'
tap 'caskroom/versions'

# install apps
cask 'appcleaner'
cask 'bartender'
cask 'ccleaner'
cask 'controlplane'
cask 'cyberduck'
cask 'dropbox'
cask 'flux'
cask 'franz'
cask 'google-chrome'
cask 'google-drive'
cask 'google-photos-backup'
cask 'iterm2'
cask 'itsycal'
cask 'keycastr'
cask 'licecap'
cask 'macdown'
cask 'messenger'
cask 'ngrok'
cask 'onyx'
cask 'plex-home-theater'
cask 'sketch'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sublime-text3'
cask 'teamviewer'
cask 'toggldesktop'
cask 'transmission'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'vlc'
cask 'vmware-fusion'
